# Dockerfile for running an ml model container with gpu (Nvidia)
# CUDA <version> and Ubuntu 22.04:
FROM nvcr.io/nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04


WORKDIR /app

# Copy the requirements file 
COPY requirements.txt .

# Install python
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev build-essential && \
    rm -rf /var/lib/apt/lists/*
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

# Install Python dependencies [ "--no-cache-dir" for reduces size ]
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code
COPY . .


# Start
CMD ["python", "main.py"]

# API port [change]
EXPOSE 5000